import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./context/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-[url('/images/vintage.jpg')] bg-no-repeat bg-left bg-fixed xl:bg-current bg-cover ${inter.className}`}
      >
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
